### ISSUE TITLE
Incorrect Download URLs

### ISSUE THREAD

**Issue by a-r-j** [amhummer/Graphinity#2]
Hiya, thanks for sharing this work (and the great documentation!)

I think the download links [here](https://github.com/amhummer/Graphinity/blob/main/data/ddg_synthetic/README.md) are outdated. It looks like these archives have been moved to: https://opig.stats.ox.ac.uk/data/downloads/affinity_dataset/

**Comment by amhummer** [comment]
That is correct – thank you very much for pointing it out! I've updated the README.
