### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by Xiaoxiao0606** [amhummer/Graphinity#3]
Hello, we have noticed your work and are very interested in it. Could you please provide more detailed code, such as the training code? Thank you!

**Comment by amhummer** [comment]
Hi, thank you for your interest. We will make the training code available upon journal publication.

**Comment by ELMIAR-0642** [comment]
Have you published your journal? When will the training code be available?

**Comment by amhummer** [comment]
Hi @ELMIAR-0642, the paper is still under review. I unfortunately do not have more information regarding a timeline for publication, and therefore release of the training code, at this point.
