### ISSUE TITLE
Request for Tool Usage and Script Assistance for Mutating Residues in a PDB File

### ISSUE THREAD

**Issue by kehan777** [amhummer/Graphinity#5]
Thank you for your outstanding work and for sharing it with us. I am interested in learning how to utilize this tool. Could you kindly provide me with the necessary scripts for its usage? For instance, if I have a pdb file (1ahw) and want to mutate residue SER at position 94 in chain A to any of the other 19 residues, could you please provide me with a list of the acceptable substitutions (ARNDCQEGHILKMFPTWYV) and the corresponding scripts?

**Comment by amhummer** [comment]
Thank you for your kind words and interest in our work!

In this work, however, we found that there is insufficient experimental data (by orders of magnitude) to accurately and generalizably predict the effects of mutations on binding affinity. As a result, our work is not intended to predict experimental ddG values.

Please let me know if you have any questions!
